import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
// eslint-disable-next-line import/no-extraneous-dependencies
import { getServerSession } from 'next-auth';
import { options } from '@/app/api/auth/[...nextauth]/options';

export const metadata: Metadata = {
    title: 'CRS',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(options);
    if (!session) {
        return redirect('/signin');
    }
    if (session && session.user && session.user.role === 'teacher') {
        return <main>{children}</main>;
    }
    return redirect(`/${session.user.role}`);
}
