import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import StoreProvider from '@/lib/react-redux/storeProvider';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import './globals.css';
import React from 'react';
import SessionProvider from '@/lib/next-auth/SessionProvider';
import AutoLogout from '@/lib/next-auth/AutoLogout';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'CRS',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <ToastContainer
                    position="top-right"
                    autoClose={1500}
                    hideProgressBar={false}
                    newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                />
                <StoreProvider>
                    <SessionProvider>
                        <AutoLogout>
                            <main>{children}</main>
                        </AutoLogout>
                    </SessionProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
